"""Request/costing PDF attached to the Jira approval ticket (increment 2.4c).

A one-page summary the approver can open from the ticket: the request details,
a components table with sizing, and a cost summary — so a supervisor can decide
to approve or reject without digging elsewhere.
"""

from datetime import datetime, timezone

from fpdf import FPDF

TEAL = (11, 85, 99)
AMBER = (180, 83, 9)
GREY = (90, 90, 90)


def build_request_pdf(req, breakdown: dict, sizing: dict) -> bytes:
    """Render the request + costing sheet as a PDF (bytes)."""
    currency = breakdown.get("currency", "AED")
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --- Title ---
    pdf.set_text_color(*TEAL)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, "Infrastructure Provisioning Request", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*GREY)
    pdf.cell(0, 6, f"Reference {req.reference}  -  for approval decision",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # --- Request details ---
    _heading(pdf, "Request details", TEAL)
    _kv(pdf, "Requester", req.requester)
    _kv(pdf, "Request type", req.request_type)
    _kv(pdf, "Project", req.project_code)
    _kv(pdf, "Cost centre", req.cost_centre_code)
    _kv(pdf, "Deployment target", req.deployment_target)
    _kv(pdf, "Environment", req.environment_name or req.target_environment)
    _kv(pdf, "Environment tier", getattr(req, "environment_tier", None))
    _kv(pdf, "Data classification", req.data_classification)
    pdf.ln(2)

    # --- Governance & ownership (increment 6.1) ---
    if req.request_type != "decommission" and (req.business_justification or req.priority):
        _heading(pdf, "Governance & ownership", TEAL)
        _kv(pdf, "Priority", req.priority)
        _kv(pdf, "Business criticality", req.business_criticality)
        _kv(pdf, "Required delivery", req.required_delivery_date)
        _kv(pdf, "Application owner", req.application_owner)
        _kv(pdf, "Business owner", req.business_owner)
        _kv(pdf, "Technical owner", req.technical_owner)
        _kv(pdf, "Environment owner", req.environment_owner)
        _kv(pdf, "Business justification", req.business_justification)
        pdf.ln(2)

    # --- Advanced options (6.5) ---
    adv = getattr(req, "advanced_options", None) or {}
    shown = {k: v for k, v in adv.items() if v not in (None, "", "none", False)}
    if shown:
        _heading(pdf, "Advanced options", TEAL)
        for k, v in shown.items():
            _kv(pdf, k.replace("_", " ").title(), "yes" if v is True else str(v))
        pdf.ln(2)

    # --- Components, sizing & cost ---
    _heading(pdf, "Components, sizing & cost", TEAL)
    cols = [("Technology", 46), ("Size", 18), ("vCPU", 14), ("RAM GB", 18),
            ("Storage GB", 22), (f"Monthly {currency}", 30)]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(*TEAL)
    pdf.set_text_color(255, 255, 255)
    for label, width in cols:
        pdf.cell(width, 8, label, border=1, align="C", fill=True)
    pdf.ln()

    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "", 9)
    lines = breakdown.get("lines", [])
    for i, comp in enumerate(sizing.get("components", [])):
        cost = lines[i] if i < len(lines) else {}
        cells = [
            (comp.get("technology_name") or "-", 46, "L"),
            (comp.get("size") or "-", 18, "C"),
            (_num(comp.get("vcpu")), 14, "C"),
            (_num(comp.get("memory_gb")), 18, "C"),
            (_num(comp.get("storage_gb")), 22, "C"),
            (f"{cost.get('monthly', 0):,.2f}", 30, "R"),
        ]
        for text, width, align in cells:
            pdf.cell(width, 7, text, border=1, align=align)
        pdf.ln()
    pdf.ln(3)

    # --- Cost summary ---
    _heading(pdf, "Cost summary", AMBER)
    totals = breakdown.get("totals", {})
    for label, key in [("One-time", "one_time"), ("Monthly", "monthly"), ("Annual", "annual")]:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(20, 20, 20)
        pdf.cell(45, 8, label, border=0)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, f"{currency} {totals.get(key, 0):,.2f}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0, 5,
        f"Generated by the Infrastructure Provisioning Portal on "
        f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}. Figures are "
        f"server-computed estimates (pricing source: {breakdown.get('pricing_source', 'mock')}).",
    )
    return bytes(pdf.output())


def _heading(pdf: FPDF, text: str, colour) -> None:
    pdf.set_text_color(*colour)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")


def _kv(pdf: FPDF, label: str, value) -> None:
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(20, 20, 20)
    pdf.cell(45, 7, label, border=0)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 7, str(value or "-"), new_x="LMARGIN", new_y="NEXT")


def _num(value) -> str:
    return str(value) if value is not None else "-"
