"""Excel (.xlsx) cost sheet for a request (increment 6.4).

A spreadsheet the approver / finance can open: a request summary, a per-component
cost table split into compute / storage / licence, category subtotals, and grand
totals. Backup / monitoring / support / network are listed as opt-in / usage-based
(Advanced Options, a later increment) rather than fabricated.

Kept alongside the one-page PDF (api/attachment.py); both are attached to the
Jira approval ticket at submission, and the Excel is downloadable from the portal.
"""

from datetime import datetime, timezone

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill

TEAL = "0B5563"
AMBER = "B45309"
HEADER_FILL = PatternFill("solid", fgColor=TEAL)
HEADER_FONT = Font(bold=True, color="FFFFFF")
BOLD = Font(bold=True)
RIGHT = Alignment(horizontal="right")


def _money(cell, value) -> None:
    cell.value = value
    cell.number_format = "#,##0.00"
    cell.alignment = RIGHT


def build_cost_sheet_xlsx(req, breakdown: dict, sizing: dict) -> bytes:
    """Render the request + costing sheet as an .xlsx (bytes)."""
    currency = breakdown.get("currency", "AED")
    by_cat = breakdown.get("by_category", {})
    totals = breakdown.get("totals", {})
    lines = breakdown.get("lines", [])
    comps = sizing.get("components", [])

    wb = Workbook()
    ws = wb.active
    ws.title = "Cost sheet"

    ws.append(["Infrastructure Provisioning — Cost Sheet"])
    ws["A1"].font = Font(bold=True, size=14, color=TEAL)
    ws.append([f"Reference {req.reference}  ·  for approval decision"])
    ws.append([])

    # --- Request summary ---
    summary = [
        ("Requester", req.requester),
        ("Request type", req.request_type),
        ("Project", req.project_code),
        ("Cost centre", req.cost_centre_code),
        ("Deployment target", req.deployment_target),
        ("Environment", req.environment_name or req.target_environment),
        ("Environment tier", getattr(req, "environment_tier", None)),
        ("Priority", getattr(req, "priority", None)),
        ("Business criticality", getattr(req, "business_criticality", None)),
    ]
    for label, value in summary:
        ws.append([label, value if value is not None else "-"])
        ws.cell(ws.max_row, 1).font = BOLD
    ws.append([])

    # --- Components, sizing & cost ---
    header_row = ws.max_row + 1
    headers = ["Technology", "Size", "vCPU", "RAM GB", "Storage GB",
               f"Compute {currency}", f"Storage {currency}", f"Licence {currency}",
               f"One-time {currency}", f"Monthly {currency}"]
    ws.append(headers)
    for col in range(1, len(headers) + 1):
        c = ws.cell(header_row, col)
        c.fill = HEADER_FILL
        c.font = HEADER_FONT

    for i, comp in enumerate(comps):
        line = lines[i] if i < len(lines) else {}
        ws.append([
            comp.get("technology_name") or "-",
            comp.get("size") or "-",
            comp.get("vcpu"),
            comp.get("memory_gb"),
            comp.get("storage_gb"),
        ])
        r = ws.max_row
        _money(ws.cell(r, 6), line.get("compute_monthly", 0))
        _money(ws.cell(r, 7), line.get("storage_monthly", 0))
        _money(ws.cell(r, 8), line.get("licence_monthly", 0))
        _money(ws.cell(r, 9), line.get("one_time", 0))
        _money(ws.cell(r, 10), line.get("monthly", 0))
    ws.append([])

    # --- Cost by category (monthly) ---
    ws.append(["Cost by category (monthly)"])
    ws.cell(ws.max_row, 1).font = Font(bold=True, color=TEAL)
    for label, key in [("Compute", "compute"), ("Storage", "storage"), ("Licence", "licence")]:
        ws.append([label])
        _money(ws.cell(ws.max_row, 2), by_cat.get(key, 0))
    # Opt-in / usage-based lines — surfaced for completeness, not priced here.
    for label in ("Backup", "Monitoring", "Support"):
        ws.append([label, "opt-in (Advanced Options)"])
        ws.cell(ws.max_row, 2).alignment = RIGHT
    ws.append(["Network", "usage-based (egress)"])
    ws.cell(ws.max_row, 2).alignment = RIGHT
    ws.append([])

    # --- Grand totals ---
    ws.append(["Totals"])
    ws.cell(ws.max_row, 1).font = Font(bold=True, color=AMBER)
    for label, key in [("One-time", "one_time"), ("Monthly", "monthly"), ("Annual", "annual")]:
        ws.append([f"{label} ({currency})"])
        ws.cell(ws.max_row, 1).font = BOLD
        _money(ws.cell(ws.max_row, 2), totals.get(key, 0))
        ws.cell(ws.max_row, 2).font = BOLD
    ws.append([])

    ws.append([
        f"Generated by the Infrastructure Provisioning Portal on "
        f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}. Server-computed estimate "
        f"(pricing source: {breakdown.get('pricing_source', 'mock')}). "
        f"Backup/monitoring/support are opt-in; network is usage-based."
    ])

    # Reasonable column widths.
    widths = [26, 14, 8, 9, 11, 14, 14, 14, 15, 15]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[chr(64 + i)].width = w

    from io import BytesIO
    buf = BytesIO()
    wb.save(buf)
    return buf.getvalue()
